<#
.SYNOPSIS
    One-time local setup: generates the HTTPS development certificate and a .env with
    strong random secrets.

.DESCRIPTION
    Safe to re-run. Existing files are left alone unless -Force is passed, so this will
    never silently rotate a password that a running database is already using.

.EXAMPLE
    ./scripts/setup.ps1
    docker compose up -d
#>
[CmdletBinding()]
param(
    [switch]$Force,
    [switch]$TrustCertificate
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$envFile = Join-Path $repoRoot '.env'
$certDir = Join-Path $env:USERPROFILE '.aspnet\https'
$certFile = Join-Path $certDir 'TicketMiser.Web.pfx'

function New-Secret {
    $bytes = New-Object byte[] 24
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    ([Convert]::ToBase64String($bytes) -replace '[+/=]', '')
}

if ((Test-Path $envFile) -and -not $Force) {
    Write-Host ".env already exists; leaving it alone (pass -Force to regenerate)." -ForegroundColor Yellow
    $certPassword = (Select-String -Path $envFile -Pattern '^CERT_PASSWORD=(.*)$').Matches.Groups[1].Value
}
else {
    $certPassword = New-Secret
    $dbPassword = New-Secret

    @"
# Local secrets. Gitignored; never commit this file.
# Generated by scripts/setup.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm').

POSTGRES_PASSWORD=$dbPassword
CERT_PASSWORD=$certPassword
CERT_PATH=`${USERPROFILE}/.aspnet/https
HTTPS_PORT=8443

# Source keys. Blank leaves a source unregistered.
TICKETMASTER_ENABLED=false
TICKETMASTER_KEY=
TICKETMASTER_INVENTORY_ENABLED=false
TICKETMASTER_INVENTORY_KEY=
DISCOVERY_FEED_ENABLED=false
SEATGEEK_ENABLED=false
SEATGEEK_CLIENT_ID=
SEATGEEK_CLIENT_SECRET=
"@ | Set-Content -Path $envFile -Encoding utf8

    Write-Host "Wrote .env with fresh secrets." -ForegroundColor Green
}

if (-not (Test-Path $certDir)) {
    New-Item -ItemType Directory -Force -Path $certDir | Out-Null
}

if ((Test-Path $certFile) -and -not $Force) {
    Write-Host "Certificate already present at $certFile" -ForegroundColor Yellow
}
else {
    dotnet dev-certs https -ep $certFile -p $certPassword | Out-Null
    Write-Host "Exported development certificate to $certFile" -ForegroundColor Green
}

if ($TrustCertificate) {
    dotnet dev-certs https --trust
}
else {
    Write-Host ""
    Write-Host "The certificate is not trusted yet. To avoid browser warnings, run:" -ForegroundColor Cyan
    Write-Host "    dotnet dev-certs https --trust" -ForegroundColor Cyan
}

# Host-side runs read the password from user-secrets, never from a committed file.
& (Join-Path $PSScriptRoot 'provision-secrets.ps1')

Write-Host ""
Write-Host "Next:" -ForegroundColor Cyan
Write-Host "    docker compose -f docker-compose.yml -f compose.dev.yml up -d postgres" -ForegroundColor White
Write-Host "    dotnet run --project src/TicketMiser.Web --launch-profile http" -ForegroundColor White
